object Versions {

    const val gradleVersion = "7.0.4"
    const val kotlinVersion = "1.6.10"
    const val coreVersion = "1.7.0"
    const val appCompatVersion = "1.4.1"
    const val materialVersion = "1.5.0"
    const val constraintLayoutVersion = "2.1.3"
    const val legacySupportVersion = "1.0.0"
    const val workRuntimeVersion = "2.7.1"
    const val jUnitVersion = "4.13.2"
    const val jUnitTestVersion = "1.1.3"
    const val espressoVersion = "3.4.0"
    const val coroutinesVersion = "1.5.2"
    const val lifecycleExtensionsVersion = "2.2.0"
    const val lifecycleVersion = "2.4.1"
    const val hiltVersion = "2.38.1"
    const val hiltLifecycleVersion = "1.0.0-alpha03"
    const val hiltCompilerVersion = "1.0.0"
    const val retrofitVersion = "2.9.0"
    const val okHttpVersion = "5.0.0-alpha.2"
    const val navigationVersion = "2.5.0-alpha03"
    const val roomVersion ="2.4.2"
    const val glideVersion = "4.12.0"
    const val lottieVersion = "5.0.2"

}
